spring.application.name=documentos-spring
spring.rabbitmq.addresses=amqp://guest:guest@localhost:5672
spring.data.mongodb.uri=mongodb://root:example@localhost:27018/examen?authSource=admin
server.port=8080
